spring:
  mvc.static-path-pattern: /static/**
  web.resources.static-locations: classpath:/static

  datasource:
    url: jdbc:postgresql://localhost:5432/demoDB
    username: usr
    password: pwd
    driver-class-name: org.postgresql.Driver
  sql.init.mode: NEVER

  flyway:
    enabled: true
    user: usr
    password: pwd
    url: jdbc:postgresql://localhost:5432/demoDB

  freemarker:
    template-loader-path: classpath:/templates
    suffix: .ftl