start256m:
	java -jar \
		-Xms256m\
		-Xmx256m\
		-XX:+HeapDumpOnOutOfMemoryError\
        -XX:HeapDumpPath=./logs/heapdump.hprof\
		-XX:+UseG1GC\
		-Xlog:gc=debug:file=./logs/gc-%p-%t.log:tags,uptime,time,level:filecount=5,filesize=10m\
		build/libs/gccheck-0.1.jar

start512m:
	java -jar \
		-Xms512m\
		-Xmx512m\
		-XX:+HeapDumpOnOutOfMemoryError\
        -XX:HeapDumpPath=./logs/heapdump.hprof\
		-XX:+UseG1GC\
		-Xlog:gc=debug:file=./logs/gc-%p-%t.log:tags,uptime,time,level:filecount=5,filesize=10m\
		build/libs/gccheck-0.1.jar

start768m:
	java -jar \
		-Xms768m\
		-Xmx768m\
		-XX:+HeapDumpOnOutOfMemoryError\
        -XX:HeapDumpPath=./logs/heapdump.hprof\
		-XX:+UseG1GC\
		-Xlog:gc=debug:file=./logs/gc-%p-%t.log:tags,uptime,time,level:filecount=5,filesize=10m\
		build/libs/gccheck-0.1.jar

start1g:
	java -jar \
		-Xms1g\
		-Xmx1g\
		-XX:+HeapDumpOnOutOfMemoryError\
        -XX:HeapDumpPath=./logs/heapdump.hprof\
		-XX:+UseG1GC\
		-Xlog:gc=debug:file=./logs/gc-%p-%t.log:tags,uptime,time,level:filecount=5,filesize=10m\
		build/libs/gccheck-0.1.jar

start2g:
	java -jar \
		-Xms2g\
		-Xmx2g\
		-XX:+HeapDumpOnOutOfMemoryError\
        -XX:HeapDumpPath=./logs/heapdump.hprof\
		-XX:+UseG1GC\
		-Xlog:gc=debug:file=./logs/gc-%p-%t.log:tags,uptime,time,level:filecount=5,filesize=10m\
		build/libs/gccheck-0.1.jar

start4g:
	java -jar \
		-Xms4g\
		-Xmx4g\
		-XX:+HeapDumpOnOutOfMemoryError\
        -XX:HeapDumpPath=./logs/heapdump.hprof\
		-XX:+UseG1GC\
		-Xlog:gc=debug:file=./logs/gc-%p-%t.log:tags,uptime,time,level:filecount=5,filesize=10m\
		build/libs/gccheck-0.1.jar

start8g:
	java -jar \
		-Xms8g\
		-Xmx8g\
		-XX:+HeapDumpOnOutOfMemoryError\
        -XX:HeapDumpPath=./logs/heapdump.hprof\
		-XX:+UseG1GC\
		-Xlog:gc=debug:file=./logs/gc-%p-%t.log:tags,uptime,time,level:filecount=5,filesize=10m\
		build/libs/gccheck-0.1.jar
