---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: homeowners-postgres
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homeowners-postgres
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: homeowners-postgres
    spec:
      containers:
        - image: library/postgres:14.4
          name: homeowners-postgres
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: homeowners
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: hosecrets
                  key: homeowners_db_password
            - name: POSTGRES_DB
              value: homeowners


---
apiVersion: v1
kind: Service
metadata:
  name: homeowners-postgres
  namespace: default
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: homeowners-postgres
  type: ClusterIP

