---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: homeowners-core
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homeowners-core
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: homeowners-core
    spec:
      containers:
        - image: registry.gitlab.com/shurupov/homeowners/core
          name: homeowners-core
          ports:
            - containerPort: 8080
          env:
            - name: SOME_VARIABLE
              value: some value from k8s 02-deployment.yml
            - name: SOME_SECRET_VARIABLE
              valueFrom:
                secretKeyRef:
                  name: dbsecret
                  key: secretword
      imagePullSecrets:
        - name: registry-credentials

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: ui
    spec:
      containers:
        - image: nginx:latest
          name: ui
          ports:
            - containerPort: 80
#      imagePullSecrets:
#        - name: regcred
