---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: homeowners-postgres
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homeowners-postgres
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: homeowners-postgres
    spec:
      containers:
        - image: library/postgres:14.4
          name: homeowners-postgres
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: homeowners
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: hosecrets
                  key: homeowners_db_password
            - name: POSTGRES_DB
              value: homeowners

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: homeowners-core
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homeowners-core
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: homeowners-core
    spec:
      containers:
        - image: registry.gitlab.com/shurupov/homeowners/core
          name: homeowners-core
          ports:
            - containerPort: 8080
          env:
            - name: SOME_VARIABLE
              value: some value from k8s 02-deployment.yml
            - name: SOME_SECRET_VARIABLE
              valueFrom:
                secretKeyRef:
                  name: hosecrets
                  key: secretword
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://homeowners-postgres.default.svc.cluster.local:5432/homeowners
            - name: SPRING_DATASOURCE_USERNAME
              value: homeowners
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: hosecrets
                  key: homeowners_db_password
            - name: LIQUIBASE_URL
              value: jdbc:postgresql://homeowners-postgres.default.svc.cluster.local:5432/homeowners
            - name: LIQUIBASE_USER
              value: homeowners
            - name: LIQUIBASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: hosecrets
                  key: homeowners_db_password
      imagePullSecrets:
        - name: registry-credentials

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: ui
    spec:
      containers:
        - image: nginx:latest
          name: ui
          ports:
            - containerPort: 80
