version: "3"
services:
  postgresdb:
    container_name: otus-postgresdb
    image: library/postgres:13.2
    environment:
      POSTGRES_USER: usr
      POSTGRES_PASSWORD: pwd
      POSTGRES_DB: demoDB
    ports:
      - "5432:5432"